# ---------------------------------- Cluster -----------------------------------
# 任意のクラスタ名を設定します。
cluster.name: test-cluster

# elasticsearch7系では必須項目
# 全てのnodeをmasterに指定する、一つだけを指定することもできる
cluster.initial_master_nodes:
  - es1
  - es2
  - es3
# ---------------------------------- Cluster -----------------------------------
# ノードにホスト名を覚え込ませる設定
# OSのホスト名を取得して設定するようにしています。
node.attr.host: ${HOSTNAME}

# 1インスタンス内にいくつノードを起動できるかの設定
# こちらを設定しないと1インスタンス内に複数ノードの起動ができません。
# 今回の最大ノード数が「3」なので3を設定します。
node.max_local_storage_nodes: 3

# ---------------------------------- Network -----------------------------------
# バインドIPアドレス
# ネットワークインタフェースが複数ある場合は、どのIPからの接続を許可するか記述する。
#（全部OKにする場合は 0.0.0.0)
network.host: 0.0.0.0

# 【解説】クラスタを構成するための要素を設定する項目
# --------------------------------- Discovery ----------------------------------

# マスター適格ノードの最定数
# マスター適格ノードの障害に備え、どこを最低数とするか指定をします。
# 「cluster.initial_master_nodesの数 / 2 +1 」で計算します。
# この数を下回るとElasticsearchの機能が停止します。
# マスターノードと候補生の数
discovery.zen.minimum_master_nodes: 2
